# -*- coding: utf-8 -*-
"""portfolio_risk_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XmdjHWxDsCrVtco3gD9xTV0T8O1CxZmI

# Portfolio Risk Agent
> **LangGraph + Claude Sonnet · Agentic portfolio risk analysis**

Multi-client portfolio risk agent using LangGraph orchestration and the Anthropic API for model selection and report generation.

**Run order:** Execute cells top to bottom. After Cell 1, restart runtime before continuing.

| Cell | Purpose |
|------|---------|
| 1 | Install dependencies |
| 2 | Imports & API key |
| 3 | Agent state definition |
| 4 | Tool: fetch market data |
| 5 | Tool: select risk model (LLM) |
| 6 | Tool: compute risk (vol, VaR, ES, beta) |
| 7 | Tool: QC checks |
| 8 | Tool: generate report (LLM) |
| 9 | LangGraph router logic |
| 10 | Build LangGraph agent |
| 11 | Dashboard renderer |
| 12 | Run agent · render tabbed dashboard |

## Cell 1 — Install dependencies
Run first, then **Runtime → Restart runtime** before proceeding.
"""

# Run this cell first, then restart runtime
!pip install langgraph anthropic yfinance pandas numpy scipy -q

"""## Cell 2 — Imports & API key
Replace `YOUR_KEY_HERE` with your Anthropic API key before running.
"""

import os
import json
import numpy as np
import pandas as pd
import yfinance as yf
from datetime import datetime, timedelta
from scipy import stats
from IPython.display import display, HTML

import anthropic
from langgraph.graph import StateGraph, END
from typing import TypedDict, Optional

# Set your Anthropic API key
os.environ["ANTHROPIC_KEY"] = "API KEY Enter Here"
client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_KEY"])

"""## Cell 3 — Agent state
`PortfolioState` is the shared typed dict that flows through every LangGraph node.
"""

class PortfolioState(TypedDict):
    # --- Inputs ---
    portfolio: dict                  # {"AAPL": 0.3, "MSFT": 0.2, ...}
    client_context: str              # e.g. "US large-cap tech, long-only"
    region: str
    asset_class: str

    # --- Tool outputs ---
    market_data: Optional[dict]
    model_config: Optional[dict]
    risk_results: Optional[dict]
    qc_flags: Optional[list]

    # --- Control ---
    qc_passed: Optional[bool]
    retry_count: int
    max_retries: int                 # ceiling on retry attempts
    error_message: Optional[str]

    # --- Final output ---
    report: Optional[str]

"""## Cell 4 — Tool: fetch market data
Downloads historical prices via `yfinance`, computes daily log returns. Lookback extends by 90d on retry.
"""

def fetch_market_data(state: PortfolioState) -> PortfolioState:
    """
    Downloads historical price data for all tickers in the portfolio.
    Computes daily log returns. Retries with extended window on failure.
    """
    print("  [Tool] Fetching market data...")
    tickers = list(state["portfolio"].keys())
    lookback_days = 365 + state["retry_count"] * 90  # extend window on retry

    end_date = datetime.today()
    start_date = end_date - timedelta(days=lookback_days)

    try:
        raw = yf.download(tickers, start=start_date, end=end_date,
                          auto_adjust=True, progress=False)["Close"]

        if isinstance(raw, pd.Series):
            raw = raw.to_frame(tickers[0])

        raw = raw.dropna(how="all")
        missing = [t for t in tickers if t not in raw.columns or raw[t].isna().mean() > 0.1]

        if missing:
            state["error_message"] = f"Insufficient data for: {missing}"
            state["qc_passed"] = False
            return state

        returns = np.log(raw / raw.shift(1)).dropna()
        weights = np.array([state["portfolio"][t] for t in tickers])

        # Portfolio-level daily returns
        portfolio_returns = (returns[tickers] * weights).sum(axis=1)

        state["market_data"] = {
            "tickers": tickers,
            "returns": returns[tickers].to_dict(orient="list"),
            "portfolio_returns": portfolio_returns.tolist(),
            "dates": portfolio_returns.index.strftime("%Y-%m-%d").tolist(),
            "lookback_days": lookback_days,
            "n_obs": len(portfolio_returns),
        }
        state["error_message"] = None
        print(f"    Loaded {len(portfolio_returns)} observations for {len(tickers)} tickers.")

    except Exception as e:
        state["error_message"] = str(e)
        state["qc_passed"] = False

    return state

"""## Cell 5 — Tool: select risk model *(LLM)*
LLM reasons about which model config fits the client mandate — the primary **agentic customization** step.

To upgrade to Opus: change `model=` to `claude-opus-4-20250514`.
"""

def select_risk_model(state: PortfolioState) -> PortfolioState:
    """
    Uses the LLM to reason about which model config suits this client's
    portfolio — region, asset class, concentration, and volatility regime.
    This is the 'agentic customization' step.
    """
    print("  [Tool] Selecting risk model via LLM reasoning...")

    tickers = state["market_data"]["tickers"]
    n_obs = state["market_data"]["n_obs"]
    region = state["region"]
    asset_class = state["asset_class"]

    # [CHANGED] Cell 5: richer prompt forces mandate-specific differentiation
    prompt = f"""You are a quantitative risk model specialist at an asset management firm.
A client has submitted the following portfolio for risk analysis:
- Tickers: {tickers}
- Region: {region}
- Asset class: {asset_class}
- Client context: {state['client_context']}
- Number of observations available: {n_obs}

You MUST select parameters that meaningfully differ by mandate type. Do NOT default
to the same config for every client. Follow these decision rules precisely:

var_method:
  - "historical": equities, HY credit, EM, concentrated or non-normal return profiles
  - "parametric": ONLY for diversified investment-grade short-to-medium duration fixed
    income (e.g. SHY, VCSH, MUB, VGSH). These have near-normal distributions.
    Do NOT use parametric for HY bonds, long-duration bonds, EM, or equities.

vol_window:
  - 60d: tech/growth equities, EM, high-turnover mandates
  - 90d: balanced or blended equity/credit mandates
  - 120d: short-duration IG fixed income or pension-style — stability over reactivity

var_confidence:
  - 0.95: standard equities or IG fixed income
  - 0.99: EM, leveraged, or highly concentrated mandates

es_confidence:
  - 0.975: Basel III standard, use for most mandates
  - 0.99: only when var_confidence is 0.99

annualization_factor:
  - 252: US equities and most DM markets
  - 250: EM Asia (fewer trading days)
  - 260: fixed income markets

vol_scalar:
  - 1.0: DM equities or investment-grade fixed income
  - 1.15: blended EM/DM portfolios
  - 1.25: pure EM or frontier market mandates

factors:
  - DM equities: ["market_beta", "sector", "size", "momentum"]
  - EM equities: ["market_beta", "country", "currency", "sector"]
  - Long-duration FI: ["duration", "credit_spread", "curve_slope", "convexity"]
  - Short-duration IG FI: ["duration", "credit_spread", "liquidity"]

Return ONLY a valid JSON object with no preamble or markdown:
{{
  "var_confidence": <float>,
  "es_confidence": <float>,
  "vol_window": <int>,
  "var_method": "historical" or "parametric",
  "annualization_factor": <int>,
  "vol_scalar": <float>,
  "factors": <list of strings>,
  "rationale": "<two sentences: what you chose and why it fits this specific mandate>"
}}"""

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=600,
        messages=[{"role": "user", "content": prompt}]
    )

    raw = response.content[0].text.strip()
    # Strip markdown fences if present
    raw = raw.replace("```json", "").replace("```", "").strip()
    config = json.loads(raw)

    # [CHANGED] Cell 5: defensive defaults so missing LLM fields never KeyError
    config.setdefault("vol_window", 60)
    config.setdefault("factors", [])
    config.setdefault("vol_scalar", 1.0)
    config.setdefault("annualization_factor", 252)
    state["model_config"] = config
    print(f"    Model: {config['var_method']} VaR @ {config['var_confidence']:.0%}, "
          f"ES @ {config['es_confidence']:.0%}, vol_scalar={config['vol_scalar']}, "
          f"vol_window={config['vol_window']}d, ann={config['annualization_factor']}")
    print(f"    Rationale: {config['rationale']}")

    return state

"""## Cell 6 — Tool: compute risk
Computes vol, VaR, ES (CVaR), market beta vs a **weighted blended benchmark** (SPY+EEM+AGG), and rolling 30d vol.
Benchmark composition is determined by classifying each ticker's geography — including US-listed EM ADRs.
"""

def compute_risk(state: PortfolioState) -> PortfolioState:
    """
    Computes:
      - Annualized volatility
      - VaR (historical simulation or parametric)
      - Expected Shortfall (CVaR) — average loss beyond VaR threshold
      - Factor exposures (OLS beta to SPY as market proxy)
      - Rolling 30-day volatility series (for dashboard chart)
    """
    print("  [Tool] Computing risk metrics...")

    cfg = state["model_config"]
    port_returns = np.array(state["market_data"]["portfolio_returns"])
    tickers = state["market_data"]["tickers"]
    all_returns = pd.DataFrame(state["market_data"]["returns"])
    weights = np.array([state["portfolio"][t] for t in tickers])

    ann = cfg["annualization_factor"]
    scalar = cfg["vol_scalar"]
    var_conf = cfg["var_confidence"]
    es_conf = cfg["es_confidence"]

    # --- Annualized volatility ---
    vol = float(port_returns.std() * np.sqrt(ann) * scalar)

    # --- VaR ---
    if cfg["var_method"] == "historical":
        var_1d = float(np.percentile(port_returns, (1 - var_conf) * 100))
    else:
        mu = port_returns.mean()
        sigma = port_returns.std()
        var_1d = float(stats.norm.ppf(1 - var_conf, mu, sigma))

    var_1d_pct = abs(var_1d)

    # --- Expected Shortfall (CVaR) ---
    # Average of all returns worse than VaR threshold
    tail_returns = port_returns[port_returns <= var_1d]
    es_1d_pct = float(abs(tail_returns.mean())) if len(tail_returns) > 0 else var_1d_pct * 1.2

    # Separately compute ES at es_confidence level
    var_es_threshold = float(np.percentile(port_returns, (1 - es_conf) * 100))
    tail_es = port_returns[port_returns <= var_es_threshold]
    es_conf_pct = float(abs(tail_es.mean())) if len(tail_es) > 0 else es_1d_pct

    # --- [CHANGED] Blended benchmark: weighted composite of SPY + EEM + AGG ---
    # For single-region portfolios this collapses to one benchmark.
    # For blended portfolios (e.g. US + EM Asia) we construct a synthetic
    # benchmark return series: w_us * SPY + w_em * EEM + w_bond * AGG.
    # This avoids the meaningless near-zero R2 that a single wrong benchmark
    # produces when the portfolio spans multiple markets.

    def classify_ticker(ticker: str) -> str:
        """
        [CHANGED] Cell 6: extended with ADR lookup so US-listed EM stocks
        (INFY, BABA, TSM etc.) correctly map to EM benchmark, not SPY.
        """
        em_suffixes = (".TW", ".KS", ".HK", ".SS", ".SZ", ".BO", ".NS",
                       ".BK", ".JK", ".KL", ".SI")
        bond_tickers = {"TLT", "IEF", "SHY", "LQD", "HYG", "AGG", "BND",
                        "VCIT", "VCSH", "MUB", "TIP", "IGIB", "VGSH", "VGIT",
                        "VGLT", "BNDX", "EMB", "PCY"}
        em_adrs = {"INFY", "WIT", "BABA", "BIDU", "JD", "PDD", "NIO", "XPEV",
                   "LI", "SE", "GRAB", "MELI", "NU", "VALE", "PBR",
                   "ITUB", "BBD", "TSM"}
        if any(ticker.endswith(s) for s in em_suffixes):
            return "em"
        if ticker in bond_tickers:
            return "bond"
        if ticker in em_adrs:
            return "em"
        return "us"

    portfolio_weights = state["portfolio"]
    w_us   = sum(w for t, w in portfolio_weights.items() if classify_ticker(t) == "us")
    w_em   = sum(w for t, w in portfolio_weights.items() if classify_ticker(t) == "em")
    w_bond = sum(w for t, w in portfolio_weights.items() if classify_ticker(t) == "bond")
    total  = w_us + w_em + w_bond or 1.0  # guard against zero

    benchmarks_needed = []
    if w_us   > 0: benchmarks_needed.append(("SPY", w_us / total))
    if w_em   > 0: benchmarks_needed.append(("EEM", w_em / total))
    if w_bond > 0: benchmarks_needed.append(("AGG", w_bond / total))

    benchmark_label = " + ".join(
        f"{w*100:.0f}% {t}" for t, w in benchmarks_needed
    )
    print(f"    Benchmark composition: {benchmark_label}")

    try:
        end_date = datetime.today()
        start_date = end_date - timedelta(days=state["market_data"]["lookback_days"])

        bm_returns_list = []
        for bm_ticker, bm_weight in benchmarks_needed:
            raw = yf.download(bm_ticker, start=start_date, end=end_date,
                              auto_adjust=True, progress=False)["Close"]
            if isinstance(raw, pd.DataFrame):
                raw = raw.squeeze()
            r_bm = np.log(raw / raw.shift(1)).dropna()
            r_bm.index = pd.to_datetime(r_bm.index).normalize()
            bm_returns_list.append(r_bm * bm_weight)

        # Sum weighted benchmark series, align on common dates
        benchmark_series = pd.concat(bm_returns_list, axis=1).dropna().sum(axis=1)

        # Build portfolio return series with normalized date index
        port_dates = pd.to_datetime(state["market_data"]["dates"]).normalize()
        port_series = pd.Series(port_returns, index=port_dates)

        # Inner join
        aligned = pd.concat([port_series, benchmark_series], axis=1, join="inner").dropna()
        aligned.columns = ["portfolio", "benchmark"]
        print(f"    Beta alignment: {len(aligned)} common dates found.")

        if len(aligned) > 30:
            y = aligned["portfolio"].values
            x = aligned["benchmark"].values
            beta, alpha, r_val, _, _ = stats.linregress(x, y)
            market_beta = float(round(beta, 3))
            r_squared = float(round(r_val**2, 3))
            print(f"    Beta: {market_beta}  R2: {r_squared}")
        else:
            print(f"    Warning: only {len(aligned)} common dates — skipping beta.")
            market_beta = None
            r_squared = None
    except Exception as e:
        print(f"    Beta calculation failed: {e}")
        market_beta = None
        r_squared = None

    # --- Per-ticker volatilities (for concentration view) ---
    ticker_vols = {
        t: float(all_returns[t].std() * np.sqrt(ann) * scalar)
        for t in tickers
    }

    # --- Rolling 30-day vol series (for chart) ---
    port_series_full = pd.Series(port_returns)
    rolling_vol = (port_series_full.rolling(30).std() * np.sqrt(ann) * scalar).dropna()

    state["risk_results"] = {
        "annualized_vol": round(vol * 100, 2),
        "var_1d_pct": round(var_1d_pct * 100, 2),
        "var_confidence": var_conf,
        "es_1d_pct": round(es_1d_pct * 100, 2),
        "es_conf_pct": round(es_conf_pct * 100, 2),
        "es_confidence": es_conf,
        "market_beta": market_beta,
        "r_squared": r_squared,
        "benchmark_label": benchmark_label,  # [CHANGED] store for dashboard display
        "ticker_vols": {k: round(v * 100, 2) for k, v in ticker_vols.items()},
        "weights": {t: state["portfolio"][t] for t in tickers},
        "rolling_vol": [round(v * 100, 2) for v in rolling_vol.tolist()],
        "rolling_vol_dates": list(range(len(rolling_vol))),
        "n_tail_obs": int(len(tail_returns)),
        "n_obs": int(len(port_returns)),
    }

    print(f"    Vol: {vol*100:.1f}%  |  VaR({var_conf:.0%}): {var_1d_pct*100:.2f}%  "
          f"|  ES({es_conf:.0%}): {es_conf_pct*100:.2f}%")

    return state

"""## Cell 7 — Tool: QC checks
Rule-based checks: data sufficiency, extreme vol, concentration, ES>VaR, low R².
Only `data_sufficiency` and `es_var_consistency` errors trigger a retry.
"""

def run_qc_checks(state: PortfolioState) -> PortfolioState:
    """
    Flags potential issues:
      - Insufficient data
      - Extreme volatility
      - High single-name concentration
      - ES/VaR ratio anomaly (ES should be > VaR)
      - Low beta fit (R² too low for market-linked portfolios)
    """
    print("  [Tool] Running QC checks...")

    flags = []
    r = state["risk_results"]
    weights = state["portfolio"]
    n_obs = r["n_obs"]

    if n_obs < 120:
        flags.append({
            "level": "ERROR",
            "message": f"Only {n_obs} observations — minimum 120 required for reliable VaR.",
            "metric": "data_sufficiency"
        })

    if r["annualized_vol"] > 60:
        flags.append({
            "level": "WARNING",
            "message": f"Annualized volatility of {r['annualized_vol']}% is extremely high.",
            "metric": "volatility"
        })

    max_weight = max(weights.values())
    max_ticker = max(weights, key=weights.get)
    if max_weight > 0.40:
        flags.append({
            "level": "WARNING",
            "message": f"High concentration: {max_ticker} = {max_weight*100:.0f}% of portfolio.",
            "metric": "concentration"
        })

    if r["es_1d_pct"] <= r["var_1d_pct"]:
        flags.append({
            "level": "ERROR",
            "message": "ES is not greater than VaR — possible data or calculation error.",
            "metric": "es_var_consistency"
        })

    # [CHANGED] Reference the actual blended benchmark label, not hardcoded "SPY"
    if r["r_squared"] is not None and r["r_squared"] < 0.15:
        bm_label = r.get("benchmark_label", "benchmark")
        flags.append({
            "level": "INFO",
            "message": (f"Low R² ({r['r_squared']}) vs {bm_label} — "
                        f"consider whether benchmark is appropriate for this mandate."),
            "metric": "market_fit"
        })

    errors = [f for f in flags if f["level"] == "ERROR"]
    state["qc_flags"] = flags
    state["qc_passed"] = len(errors) == 0

    if flags:
        for f in flags:
            print(f"    [{f['level']}] {f['message']}")
    else:
        print("    All QC checks passed.")

    return state

"""## Cell 8 — Tool: generate report *(LLM)*
Synthesizes all tool outputs into a structured JSON report with headline, risk level, findings, and interpretations.
"""

def generate_report(state: PortfolioState) -> PortfolioState:
    """
    LLM synthesizes all tool outputs into a structured client-facing
    risk report. Returns JSON for the dashboard renderer.
    """
    print("  [Tool] Generating client report...")

    r = state["risk_results"]
    cfg = state["model_config"]
    flags = state["qc_flags"]
    portfolio = state["portfolio"]

    prompt = f"""You are a senior portfolio risk analyst. Write a structured risk report for this client.

Portfolio: {json.dumps(portfolio)}
Client context: {state['client_context']}
Region: {state['region']} | Asset class: {state['asset_class']}

Risk metrics computed:
- Annualized volatility: {r['annualized_vol']}%
- 1-day VaR ({r['var_confidence']:.0%} confidence): {r['var_1d_pct']}%
- 1-day Expected Shortfall ({r['es_confidence']:.0%}): {r['es_conf_pct']}%
  (On the worst days beyond VaR, average loss is {r['es_1d_pct']}%)
- Market beta vs {r.get('benchmark_label','blended benchmark')}: {r['market_beta']} (R²={r['r_squared']})
- Benchmark note: beta and R² are computed against the blended benchmark above, not necessarily SPY
- Tail observations used for ES: {r['n_tail_obs']} out of {r['n_obs']}

Model used: {cfg['var_method']} VaR, vol scalar={cfg['vol_scalar']}
Model rationale: {cfg['rationale']}

QC flags raised: {json.dumps(flags)}

Return ONLY a valid JSON object with no markdown or preamble:
{{
  "headline": "<one sentence executive summary>",
  "risk_level": "LOW" or "MODERATE" or "HIGH" or "VERY HIGH",
  "key_findings": ["<finding 1>", "<finding 2>", "<finding 3>"],
  "var_interpretation": "<plain English explanation of the VaR number>",
  "es_interpretation": "<plain English explanation of ES and why it matters beyond VaR>",
  "model_note": "<one sentence on why this model config was chosen for this client>",
  "recommendations": ["<rec 1>", "<rec 2>"],
  "qc_summary": "<one sentence summarizing QC status>"
}}"""

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1000,
        messages=[{"role": "user", "content": prompt}]
    )

    raw = response.content[0].text.strip()
    raw = raw.replace("```json", "").replace("```", "").strip()
    report_data = json.loads(raw)

    state["report"] = json.dumps(report_data)
    print(f"    Risk level assessed: {report_data['risk_level']}")
    print(f"    Headline: {report_data['headline']}")

    return state

"""## Cell 9 — LangGraph router logic
`should_retry` only retries for data-fixable errors. Concentration and vol warnings never trigger retry.
`check_data_loaded` short-circuits to report if initial fetch fails.
"""

def should_retry(state: PortfolioState) -> str:
    """
    After QC: only retry if the specific error is data-fixable
    (data_sufficiency or es_var_consistency) AND we haven't hit max_retries.
    Concentration warnings, high vol, low R2 are portfolio facts —
    retrying won't change them, so we proceed and let the report flag them.
    """
    retryable_metrics = {"data_sufficiency", "es_var_consistency"}
    error_flags = [f for f in state["qc_flags"] if f["level"] == "ERROR"]
    retryable_errors = [f for f in error_flags if f["metric"] in retryable_metrics]

    if retryable_errors and state["retry_count"] < state["max_retries"]:
        print(f"  [Router] Retryable error found — attempt "
              f"{state['retry_count'] + 1}/{state['max_retries']}. "
              f"Extending data window...")
        state["retry_count"] += 1
        return "retry"

    if error_flags and not retryable_errors:
        print("  [Router] Errors present but not data-fixable — proceeding with flags.")
    elif state["retry_count"] >= state["max_retries"]:
        print(f"  [Router] Max retries ({state['max_retries']}) reached — proceeding with flags.")

    return "proceed"


def check_data_loaded(state: PortfolioState) -> str:
    """After fetch: if data load failed, skip to report with error."""
    if state.get("error_message") and not state.get("market_data"):
        return "error"
    return "ok"

"""## Cell 10 — Build LangGraph agent
Assembles the graph: nodes, edges, and conditional routing. The retry loop is the key agentic behavior.
"""

def build_agent() -> StateGraph:

    graph = StateGraph(PortfolioState)

    # Add nodes
    graph.add_node("fetch_market_data", fetch_market_data)
    graph.add_node("select_risk_model", select_risk_model)
    graph.add_node("compute_risk", compute_risk)
    graph.add_node("run_qc_checks", run_qc_checks)
    graph.add_node("generate_report", generate_report)

    # Entry point
    graph.set_entry_point("fetch_market_data")

    # fetch → select or error
    graph.add_conditional_edges(
        "fetch_market_data",
        check_data_loaded,
        {"ok": "select_risk_model", "error": "generate_report"}
    )

    # Linear steps
    graph.add_edge("select_risk_model", "compute_risk")
    graph.add_edge("compute_risk", "run_qc_checks")

    # QC → retry loop or proceed
    graph.add_conditional_edges(
        "run_qc_checks",
        should_retry,
        {"retry": "fetch_market_data", "proceed": "generate_report"}
    )

    graph.add_edge("generate_report", END)

    return graph.compile()

"""## Cell 11 — Dashboard renderer *(single client)*
Builds a dark-theme HTML dashboard for a single `PortfolioState`. Called by Cell 12.
"""

def render_dashboard(state: PortfolioState) -> None:
    """
    Renders a polished dark-theme dashboard inline in Google Colab
    using IPython.display.HTML
    """
    r = state["risk_results"]
    report = json.loads(state["report"])
    flags = state["qc_flags"]
    weights = state["portfolio"]
    cfg = state["model_config"]

    risk_colors = {
        "LOW": "#22c55e",
        "MODERATE": "#f59e0b",
        "HIGH": "#f97316",
        "VERY HIGH": "#ef4444"
    }
    risk_color = risk_colors.get(report["risk_level"], "#f59e0b")

    # Build allocation bars
    allocation_html = ""
    for ticker, w in sorted(weights.items(), key=lambda x: -x[1]):
        ticker_vol = r["ticker_vols"].get(ticker, 0)
        allocation_html += f"""
        <div class="alloc-row">
          <span class="alloc-ticker">{ticker}</span>
          <div class="alloc-bar-wrap">
            <div class="alloc-bar" style="width:{w*100:.0f}%"></div>
          </div>
          <span class="alloc-pct">{w*100:.0f}%</span>
          <span class="alloc-vol">σ {ticker_vol:.1f}%</span>
        </div>"""

    # Build QC flags
    flag_html = ""
    if not flags:
        flag_html = '<div class="qc-ok">✓ All quality checks passed</div>'
    else:
        level_icons = {"ERROR": "✕", "WARNING": "⚠", "INFO": "ℹ"}
        level_cls = {"ERROR": "flag-error", "WARNING": "flag-warn", "INFO": "flag-info"}
        for f in flags:
            icon = level_icons.get(f["level"], "•")
            cls = level_cls.get(f["level"], "flag-info")
            flag_html += f'<div class="qc-flag {cls}">{icon} {f["message"]}</div>'

    # Build findings list
    findings_html = "".join(
        f'<li>{f}</li>' for f in report["key_findings"]
    )
    recs_html = "".join(
        f'<li>{r_}</li>' for r_ in report["recommendations"]
    )

    # Rolling vol sparkline (simple SVG)
    rolling = r["rolling_vol"]
    if rolling:
        max_v = max(rolling) or 1
        min_v = min(rolling)
        w_svg = 320
        h_svg = 60
        pts = []
        for i, v in enumerate(rolling):
            x = int(i / (len(rolling) - 1) * w_svg) if len(rolling) > 1 else 0
            y = int(h_svg - (v - min_v) / (max_v - min_v + 0.001) * (h_svg - 8))
            pts.append(f"{x},{y}")
        sparkline = f"""
        <svg viewBox="0 0 {w_svg} {h_svg}" width="100%" height="{h_svg}"
             style="display:block;">
          <polyline points="{' '.join(pts)}" fill="none"
                    stroke="#f59e0b" stroke-width="1.5" stroke-linejoin="round"/>
        </svg>"""
    else:
        sparkline = "<p style='color:#666;font-size:12px'>Insufficient data for chart</p>"


    pill_method = 'pill pill-highlight' if cfg['var_method'] != 'historical' else 'pill'
    pill_varc   = 'pill pill-highlight' if cfg['var_confidence'] != 0.95 else 'pill'
    pill_esc    = 'pill pill-highlight' if cfg['es_confidence'] != 0.975 else 'pill'
    pill_ann    = 'pill pill-highlight' if cfg['annualization_factor'] != 252 else 'pill'
    pill_scalar = 'pill pill-highlight' if cfg['vol_scalar'] != 1.0 else 'pill'
    pill_vw     = 'pill pill-highlight' if cfg.get('vol_window', 60) != 60 else 'pill'
    factors_pills = ''.join(f'<div class="pill"><span>{f}</span></div>' for f in cfg.get('factors', []))
    factors_section = f'<div style="margin-top:10px;"><div class="panel-title" style="border:none;padding:0;margin-bottom:6px;">Factors</div><div class="model-pills">{factors_pills}</div></div>' if cfg.get('factors') else ''

    html = f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap" rel="stylesheet">
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #0d0f14;
    color: #e2e8f0;
    font-family: 'DM Sans', sans-serif;
    font-size: 13px;
    padding: 20px;
  }}

  .dashboard {{
    max-width: 960px;
    margin: 0 auto;
  }}

  /* Header */
  .header {{
    border-bottom: 1px solid #1e2330;
    padding-bottom: 16px;
    margin-bottom: 24px;
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 16px;
  }}
  .header-left h1 {{
    font-size: 18px;
    font-weight: 600;
    letter-spacing: -0.3px;
    color: #f1f5f9;
  }}
  .header-left .subtitle {{
    color: #64748b;
    font-size: 12px;
    margin-top: 4px;
    font-family: 'DM Mono', monospace;
  }}
  .risk-badge {{
    background: {risk_color}18;
    border: 1px solid {risk_color}55;
    color: {risk_color};
    font-family: 'DM Mono', monospace;
    font-size: 11px;
    font-weight: 500;
    padding: 4px 12px;
    border-radius: 4px;
    letter-spacing: 1px;
    white-space: nowrap;
    margin-top: 2px;
  }}

  /* Headline */
  .headline {{
    background: #131620;
    border-left: 3px solid {risk_color};
    padding: 12px 16px;
    border-radius: 0 6px 6px 0;
    margin-bottom: 24px;
    color: #cbd5e1;
    line-height: 1.6;
    font-size: 13px;
  }}

  /* Metric cards row */
  .metrics-row {{
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 12px;
    margin-bottom: 20px;
  }}
  .metric-card {{
    background: #131620;
    border: 1px solid #1e2330;
    border-radius: 8px;
    padding: 14px 16px;
  }}
  .metric-card .label {{
    color: #64748b;
    font-size: 10px;
    font-family: 'DM Mono', monospace;
    letter-spacing: 0.8px;
    text-transform: uppercase;
    margin-bottom: 6px;
  }}
  .metric-card .value {{
    font-size: 22px;
    font-weight: 600;
    font-family: 'DM Mono', monospace;
    color: #f1f5f9;
    letter-spacing: -0.5px;
  }}
  .metric-card .sub {{
    color: #64748b;
    font-size: 10px;
    margin-top: 4px;
  }}
  .metric-card.highlight {{
    border-color: {risk_color}44;
    background: {risk_color}0a;
  }}
  .metric-card.highlight .value {{
    color: {risk_color};
  }}

  /* Two column layout */
  .two-col {{
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 16px;
    margin-bottom: 16px;
  }}
  .three-col {{
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    gap: 16px;
    margin-bottom: 16px;
  }}

  /* Panels */
  .panel {{
    background: #131620;
    border: 1px solid #1e2330;
    border-radius: 8px;
    padding: 16px;
  }}
  .panel-title {{
    font-size: 10px;
    font-family: 'DM Mono', monospace;
    letter-spacing: 1px;
    text-transform: uppercase;
    color: #475569;
    margin-bottom: 12px;
    padding-bottom: 8px;
    border-bottom: 1px solid #1e2330;
  }}

  /* Allocation bars */
  .alloc-row {{
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 8px;
  }}
  .alloc-ticker {{
    font-family: 'DM Mono', monospace;
    font-size: 11px;
    color: #94a3b8;
    width: 44px;
    flex-shrink: 0;
  }}
  .alloc-bar-wrap {{
    flex: 1;
    background: #1e2330;
    border-radius: 2px;
    height: 6px;
    overflow: hidden;
  }}
  .alloc-bar {{
    height: 100%;
    background: #3b82f6;
    border-radius: 2px;
    max-width: 100%;
  }}
  .alloc-pct {{
    font-family: 'DM Mono', monospace;
    font-size: 10px;
    color: #64748b;
    width: 30px;
    text-align: right;
    flex-shrink: 0;
  }}
  .alloc-vol {{
    font-family: 'DM Mono', monospace;
    font-size: 10px;
    color: #475569;
    width: 52px;
    text-align: right;
    flex-shrink: 0;
  }}

  /* Findings & Recs */
  .panel ul {{
    padding-left: 14px;
    color: #94a3b8;
    line-height: 1.8;
    font-size: 12px;
  }}
  .panel ul li {{
    margin-bottom: 4px;
  }}

  /* Interpretation blocks */
  .interp-block {{
    margin-bottom: 10px;
  }}
  .interp-block .interp-label {{
    font-size: 10px;
    font-family: 'DM Mono', monospace;
    color: #475569;
    text-transform: uppercase;
    letter-spacing: 0.8px;
    margin-bottom: 4px;
  }}
  .interp-block p {{
    color: #94a3b8;
    font-size: 12px;
    line-height: 1.7;
  }}

  /* QC flags */
  .qc-ok {{
    color: #22c55e;
    font-family: 'DM Mono', monospace;
    font-size: 11px;
    padding: 6px 0;
  }}
  .qc-flag {{
    font-size: 11px;
    padding: 6px 10px;
    border-radius: 4px;
    margin-bottom: 6px;
    font-family: 'DM Mono', monospace;
    line-height: 1.5;
  }}
  .flag-error {{ background: #ef444415; border-left: 2px solid #ef4444; color: #fca5a5; }}
  .flag-warn  {{ background: #f59e0b15; border-left: 2px solid #f59e0b; color: #fcd34d; }}
  .flag-info  {{ background: #3b82f615; border-left: 2px solid #3b82f6; color: #93c5fd; }}

  /* Model info */
  .model-pills {{
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
    margin-top: 8px;
  }}
  .pill {{
    background: #1e2330;
    border: 1px solid #2d3548;
    color: #94a3b8;
    font-family: 'DM Mono', monospace;
    font-size: 10px;
    padding: 3px 8px;
    border-radius: 3px;
  }}
  .pill span {{
    color: #f1f5f9;
    font-weight: 500;
  }}
  /* [CHANGED] Cell 11: amber highlight for non-default values */
  .pill-highlight {{ background: #f59e0b18; border-color: #f59e0b55; color: #fcd34d; }}
  .pill-highlight span {{ color: #f59e0b; }}

  /* Footer */
  .footer {{
    margin-top: 20px;
    padding-top: 12px;
    border-top: 1px solid #1e2330;
    color: #334155;
    font-size: 10px;
    font-family: 'DM Mono', monospace;
    display: flex;
    justify-content: space-between;
  }}
</style>
</head>
<body>
<div class="dashboard">

  <!-- Header -->
  <div class="header">
    <div class="header-left">
      <h1>Portfolio Risk Report</h1>
      <div class="subtitle">{state['client_context']} · {state['region']} · {state['asset_class']}</div>
    </div>
    <div class="risk-badge">RISK: {report['risk_level']}</div>
  </div>

  <!-- Headline -->
  <div class="headline">{report['headline']}</div>

  <!-- Metric cards -->
  <div class="metrics-row">
    <div class="metric-card">
      <div class="label">Ann. Volatility</div>
      <div class="value">{r['annualized_vol']}%</div>
      <div class="sub">{cfg['vol_window']}d rolling window</div>
    </div>
    <div class="metric-card highlight">
      <div class="label">VaR 1-Day ({r['var_confidence']:.0%})</div>
      <div class="value">{r['var_1d_pct']}%</div>
      <div class="sub">{cfg['var_method']}</div>
    </div>
    <div class="metric-card highlight">
      <div class="label">Exp. Shortfall ({r['es_confidence']:.0%})</div>
      <div class="value">{r['es_conf_pct']}%</div>
      <div class="sub">avg tail loss beyond VaR</div>
    </div>
    <div class="metric-card">
      <div class="label">Market Beta</div>
      <div class="value">{r['market_beta'] if r['market_beta'] is not None else 'N/A'}</div>
      <!-- [CHANGED] Cell 11: show benchmark label -->
      <div class="sub">R² = {r['r_squared'] if r['r_squared'] is not None else 'N/A'} · {r.get('benchmark_label','benchmark')}</div>
    </div>
  </div>

  <!-- Row 2: Allocation + Rolling vol -->
  <div class="two-col">
    <div class="panel">
      <div class="panel-title">Portfolio Allocation</div>
      {allocation_html}
    </div>
    <div class="panel">
      <div class="panel-title">Rolling 30-Day Volatility (annualised)</div>
      {sparkline}
      <div style="display:flex;justify-content:space-between;margin-top:4px;">
        <span style="font-family:'DM Mono',monospace;font-size:10px;color:#475569">Start</span>
        <span style="font-family:'DM Mono',monospace;font-size:10px;color:#f59e0b">
          Current: {r['rolling_vol'][-1] if r['rolling_vol'] else 'N/A'}%
        </span>
        <span style="font-family:'DM Mono',monospace;font-size:10px;color:#475569">Today</span>
      </div>
    </div>
  </div>

  <!-- [CHANGED] Cell 11: Row 3 = Model config + Findings -->
  <div class="two-col">
    <div class="panel">
      <div class="panel-title">Model Configuration</div>
      <p style="color:#64748b;font-size:11px;line-height:1.6;margin-bottom:10px;">
        {report['model_note']}
      </p>
      <div class="model-pills">
        <div class="{pill_method}">Method <span>{cfg['var_method']}</span></div>
        <div class="{pill_varc}">VaR conf <span>{cfg['var_confidence']:.0%}</span></div>
        <div class="{pill_esc}">ES conf <span>{cfg['es_confidence']:.0%}</span></div>
        <div class="{pill_ann}">Ann. factor <span>{cfg['annualization_factor']}</span></div>
        <div class="{pill_scalar}">Vol scalar <span>{cfg['vol_scalar']}</span></div>
        <div class="{pill_vw}">Vol window <span>{cfg.get('vol_window',60)}d</span></div>
      </div>
      {factors_section}
    </div>
    <div class="panel">
      <div class="panel-title">Key Findings</div>
      <ul>{findings_html}</ul>
      <div style="margin-top:14px;" class="panel-title">Recommendations</div>
      <ul>{recs_html}</ul>
    </div>
  </div>

  <!-- [CHANGED] Cell 11: Row 4 = Interpretation + QC -->
  <div class="two-col">
    <div class="panel">
      <div class="panel-title">Risk Interpretation</div>
      <div class="interp-block">
        <div class="interp-label">VaR</div>
        <p>{report['var_interpretation']}</p>
      </div>
      <div class="interp-block">
        <div class="interp-label">Expected Shortfall</div>
        <p>{report['es_interpretation']}</p>
      </div>
    </div>
    <div class="panel">
      <div class="panel-title">QC Check Results</div>
      {flag_html}
    </div>
  </div>

  <!-- Footer -->
  <div class="footer">
    <span>Generated by Portfolio Risk Agent · LangGraph + Claude</span>
    <span>{datetime.today().strftime('%Y-%m-%d %H:%M')} UTC</span>
  </div>

</div>
</body>
</html>"""

    display(HTML(html))

"""## Cell 12 — Run agent · multi-client tabbed dashboard
Four client scenarios run independently. Non-default model parameters highlighted in **amber**.

| Client | Expected model behavior |
|--------|-------------------------|
| US Tech | Historical VaR, vol_scalar 1.0, 60d window |
| EM Asia | Historical VaR, vol_scalar 1.2, ann_factor 250, EEM benchmark |
| US Bonds | Historical VaR, 90d window, AGG benchmark |
| IG Short Dur | **Parametric VaR**, 120d window, ann_factor 260 |
"""

# Three client scenarios that showcase model customization.
# The agent runs independently for each — different region/asset class
# → LLM selects different model configs → dashboard shows the difference.

CLIENT_SCENARIOS = [
    {
        "name": "US Tech",
        "portfolio": {"AAPL": 0.25, "MSFT": 0.20, "GOOGL": 0.20, "AMZN": 0.15, "NVDA": 0.20},
        "client_context": "US large-cap technology, long-only equity portfolio",
        "region": "North America",
        "asset_class": "Equities",
    },
    {
        "name": "EM Asia",
        "portfolio": {"2330.TW": 0.30, "005930.KS": 0.25, "9988.HK": 0.25, "INFY": 0.20},
        "client_context": "Emerging market Asia technology and semiconductor mandate, long-only",
        "region": "Emerging Markets Asia",
        "asset_class": "Equities",
    },
    {
        "name": "US Bonds",
        "portfolio": {"TLT": 0.35, "IEF": 0.30, "LQD": 0.20, "HYG": 0.15},
        "client_context": "US fixed income blend: long-duration treasuries, IG and HY credit",
        "region": "North America",
        "asset_class": "Fixed Income",
    },
    {
        # [CHANGED] Cell 12: fourth client — diversified IG short-duration fixed income.
        # Designed to trigger parametric VaR: all IG-rated, liquid, short maturity,
        # near-normal return distribution. No HY, no EM, no duration risk.
        "name": "IG Short Dur",
        "portfolio": {"SHY": 0.30, "VCSH": 0.30, "MUB": 0.25, "VGSH": 0.15},
        "client_context": (
            "Conservative short-duration investment-grade fixed income mandate. "
            "All holdings are US IG-rated and liquid with maturities under 5 years. "
            "Pension fund overlay requiring stable, normally-distributed risk estimates. "
            "No high-yield, no EM exposure, no significant duration risk."
        ),
        "region": "North America",
        "asset_class": "Fixed Income - Investment Grade Short Duration",
    },
]


def make_initial_state(scenario: dict) -> PortfolioState:
    return {
        "portfolio": scenario["portfolio"],
        "client_context": scenario["client_context"],
        "region": scenario["region"],
        "asset_class": scenario["asset_class"],
        "market_data": None,
        "model_config": None,
        "risk_results": None,
        "qc_flags": None,
        "qc_passed": None,
        "retry_count": 0,
        "max_retries": 2,
        "error_message": None,
        "report": None,
    }


def build_dashboard_html(all_results: list) -> str:
    """
    Renders a tabbed multi-client dashboard. Each tab is one client scenario.
    Tabs switch client view without re-running the agent.
    """
    import json as _json
    from datetime import datetime as _dt

    risk_colors = {
        "LOW": "#22c55e",
        "MODERATE": "#f59e0b",
        "HIGH": "#f97316",
        "VERY HIGH": "#ef4444"
    }

    def build_tab_content(state, idx):
        r = state["risk_results"]
        report = _json.loads(state["report"])
        flags = state["qc_flags"]
        weights = state["portfolio"]
        cfg = state["model_config"]
        risk_color = risk_colors.get(report["risk_level"], "#f59e0b")

        # Allocation bars
        alloc_html = ""
        for ticker, w in sorted(weights.items(), key=lambda x: -x[1]):
            ticker_vol = r["ticker_vols"].get(ticker, 0)
            alloc_html += f"""
            <div class="alloc-row">
              <span class="alloc-ticker">{ticker}</span>
              <div class="alloc-bar-wrap">
                <div class="alloc-bar" style="width:{w*100:.0f}%"></div>
              </div>
              <span class="alloc-pct">{w*100:.0f}%</span>
              <span class="alloc-vol">\u03c3 {ticker_vol:.1f}%</span>
            </div>"""

        # QC flags
        flag_html = ""
        if not flags:
            flag_html = '<div class="qc-ok">\u2713 All quality checks passed</div>'
        else:
            level_icons = {"ERROR": "\u2715", "WARNING": "\u26a0", "INFO": "\u2139"}
            level_cls = {"ERROR": "flag-error", "WARNING": "flag-warn", "INFO": "flag-info"}
            for f in flags:
                icon = level_icons.get(f["level"], "\u2022")
                cls = level_cls.get(f["level"], "flag-info")
                flag_html += f'<div class="qc-flag {cls}">{icon} {f["message"]}</div>'

        findings_html = "".join(f"<li>{x}</li>" for x in report["key_findings"])
        recs_html = "".join(f"<li>{x}</li>" for x in report["recommendations"])

        # Sparkline
        rolling = r["rolling_vol"]
        sparkline = ""
        if rolling:
            max_v = max(rolling) or 1
            min_v = min(rolling)
            w_svg, h_svg = 320, 60
            pts = []
            for i, v in enumerate(rolling):
                sx = int(i / (len(rolling) - 1) * w_svg) if len(rolling) > 1 else 0
                sy = int(h_svg - (v - min_v) / (max_v - min_v + 0.001) * (h_svg - 8))
                pts.append(f"{sx},{sy}")
            sparkline = f'''
            <svg viewBox="0 0 {w_svg} {h_svg}" width="100%" height="{h_svg}" style="display:block;">
              <polyline points="{" ".join(pts)}" fill="none"
                        stroke="#f59e0b" stroke-width="1.5" stroke-linejoin="round"/>
            </svg>'''

        beta_val = r["market_beta"] if r["market_beta"] is not None else "N/A"
        r2_val = r["r_squared"] if r["r_squared"] is not None else "N/A"

        # [CHANGED] Cell 12: pre-compute pill CSS classes to fix highlight rendering bug
        def _pc(cond): return "pill pill-highlight" if cond else "pill"
        p_method = _pc(cfg["var_method"] != "historical")
        p_varc   = _pc(cfg["var_confidence"] != 0.95)
        p_esc    = _pc(cfg["es_confidence"] != 0.975)
        p_ann    = _pc(cfg["annualization_factor"] != 252)
        p_scalar = _pc(cfg["vol_scalar"] != 1.0)
        p_vw     = _pc(cfg.get("vol_window", 60) != 60)
        _fpills  = "".join(f'<div class="pill"><span>{f}</span></div>' for f in cfg.get("factors", []))
        factors_html = (f'<div style="margin-top:10px;"><div class="panel-title" style="border:none;padding:0;margin-bottom:6px;">Factors</div><div class="model-pills">{_fpills}</div></div>') if cfg.get("factors") else ""

        return f'''
        <div class="tab-pane" id="pane-{idx}">

          <div class="headline" style="border-left-color:{risk_color}">
            {report["headline"]}
          </div>

          <div class="metrics-row">
            <div class="metric-card">
              <div class="label">Ann. Volatility</div>
              <div class="value">{r["annualized_vol"]}%</div>
              <div class="sub">{cfg["vol_window"]}d window · scalar {cfg["vol_scalar"]}</div>
            </div>
            <div class="metric-card" style="border-color:{risk_color}44;background:{risk_color}0a;">
              <div class="label">VaR 1-Day ({r["var_confidence"]:.0%})</div>
              <div class="value" style="color:{risk_color}">{r["var_1d_pct"]}%</div>
              <div class="sub">{cfg["var_method"]}</div>
            </div>
            <div class="metric-card" style="border-color:{risk_color}44;background:{risk_color}0a;">
              <div class="label">Exp. Shortfall ({r["es_confidence"]:.0%})</div>
              <div class="value" style="color:{risk_color}">{r["es_conf_pct"]}%</div>
              <div class="sub">avg tail loss beyond VaR</div>
            </div>
            <div class="metric-card">
              <div class="label">Market Beta</div>
              <div class="value">{beta_val}</div>
              <div class="sub">R&#178; = {r2_val} &middot; {r.get("benchmark_label","benchmark")}</div>
            </div>
          </div>

          <div class="two-col">
            <div class="panel">
              <div class="panel-title">Portfolio Allocation</div>
              {alloc_html}
            </div>
            <div class="panel">
              <div class="panel-title">Rolling 30-Day Volatility (annualised)</div>
              {sparkline}
              <div style="display:flex;justify-content:space-between;margin-top:4px;">
                <span style="font-family:'DM Mono',monospace;font-size:10px;color:#475569">Start</span>
                <span style="font-family:'DM Mono',monospace;font-size:10px;color:#f59e0b">
                  Current: {rolling[-1] if rolling else "N/A"}%
                </span>
                <span style="font-family:'DM Mono',monospace;font-size:10px;color:#475569">Today</span>
              </div>
            </div>
          </div>

          <!-- Row 3: Model config + Key Findings -->
          <div class="two-col">
            <div class="panel">
              <div class="panel-title">Model Configuration</div>
              <p style="color:#64748b;font-size:11px;line-height:1.6;margin-bottom:10px;">
                {report["model_note"]}
              </p>
              <div class="model-pills">
                <div class="{p_method}">Method <span>{cfg["var_method"]}</span></div>
                <div class="{p_varc}">VaR conf <span>{cfg["var_confidence"]:.0%}</span></div>
                <div class="{p_esc}">ES conf <span>{cfg["es_confidence"]:.0%}</span></div>
                <div class="{p_ann}">Ann. factor <span>{cfg["annualization_factor"]}</span></div>
                <div class="{p_scalar}">Vol scalar <span>{cfg["vol_scalar"]}</span></div>
                <div class="{p_vw}">Vol window <span>{cfg.get("vol_window",60)}d</span></div>
              </div>
              {factors_html}
            </div>
            <div class="panel">
              <div class="panel-title">Key Findings</div>
              <ul>{findings_html}</ul>
              <div style="margin-top:14px;" class="panel-title">Recommendations</div>
              <ul>{recs_html}</ul>
            </div>
          </div>

          <!-- Row 4: Risk Interpretation + QC -->
          <div class="two-col">
            <div class="panel">
              <div class="panel-title">Risk Interpretation</div>
              <div class="interp-block">
                <div class="interp-label">VaR</div>
                <p>{report["var_interpretation"]}</p>
              </div>
              <div class="interp-block" style="margin-top:12px;">
                <div class="interp-label">Expected Shortfall</div>
                <p>{report["es_interpretation"]}</p>
              </div>
            </div>
            <div class="panel">
              <div class="panel-title">QC Check Results</div>
              {flag_html}
            </div>
          </div>

        </div>'''

    # Build tab buttons and panes
    tab_buttons = ""
    tab_panes = ""
    for i, (scenario, state) in enumerate(all_results):
        report = _json.loads(state["report"])
        risk_color = risk_colors.get(report["risk_level"], "#f59e0b")
        active = "active" if i == 0 else ""
        tab_buttons += f'''
        <button class="tab-btn {active}" onclick="switchTab({i})" id="tab-btn-{i}">
          <span class="tab-name">{scenario["name"]}</span>
          <span class="tab-badge" style="background:{risk_color}22;color:{risk_color};border-color:{risk_color}44">
            {report["risk_level"]}
          </span>
        </button>'''
        pane_html = build_tab_content(state, i)
        display_style = "block" if i == 0 else "none"
        tab_panes += f'<div style="display:{display_style}" id="pane-wrap-{i}">{pane_html}</div>'

    ts = _dt.today().strftime("%Y-%m-%d %H:%M")

    return f'''<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap" rel="stylesheet">
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #0d0f14;
    color: #e2e8f0;
    font-family: 'DM Sans', sans-serif;
    font-size: 13px;
    padding: 20px;
  }}
  .dashboard {{ max-width: 980px; margin: 0 auto; }}

  .header {{
    border-bottom: 1px solid #1e2330;
    padding-bottom: 14px;
    margin-bottom: 20px;
    display: flex;
    align-items: center;
    justify-content: space-between;
  }}
  .header h1 {{ font-size: 17px; font-weight: 600; color: #f1f5f9; letter-spacing: -0.3px; }}
  .header .sub {{ color: #475569; font-size: 11px; font-family: 'DM Mono', monospace; margin-top: 3px; }}

  /* Tabs */
  .tab-bar {{
    display: flex;
    gap: 8px;
    margin-bottom: 20px;
    border-bottom: 1px solid #1e2330;
    padding-bottom: 0;
  }}
  .tab-btn {{
    background: none;
    border: none;
    border-bottom: 2px solid transparent;
    padding: 8px 14px 10px;
    cursor: pointer;
    display: flex;
    align-items: center;
    gap: 8px;
    color: #475569;
    font-family: 'DM Sans', sans-serif;
    font-size: 13px;
    transition: color 0.15s;
    margin-bottom: -1px;
  }}
  .tab-btn:hover {{ color: #94a3b8; }}
  .tab-btn.active {{ color: #f1f5f9; border-bottom-color: #3b82f6; }}
  .tab-name {{ font-weight: 500; }}
  .tab-badge {{
    font-family: 'DM Mono', monospace;
    font-size: 9px;
    font-weight: 500;
    padding: 2px 6px;
    border-radius: 3px;
    border: 1px solid;
    letter-spacing: 0.5px;
  }}

  /* Headline */
  .headline {{
    background: #131620;
    border-left: 3px solid #f59e0b;
    padding: 11px 14px;
    border-radius: 0 6px 6px 0;
    margin-bottom: 20px;
    color: #cbd5e1;
    line-height: 1.6;
    font-size: 13px;
  }}

  /* Metric cards */
  .metrics-row {{
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 10px;
    margin-bottom: 16px;
  }}
  .metric-card {{
    background: #131620;
    border: 1px solid #1e2330;
    border-radius: 8px;
    padding: 13px 15px;
  }}
  .metric-card .label {{
    color: #64748b;
    font-size: 10px;
    font-family: 'DM Mono', monospace;
    letter-spacing: 0.8px;
    text-transform: uppercase;
    margin-bottom: 5px;
  }}
  .metric-card .value {{
    font-size: 21px;
    font-weight: 600;
    font-family: 'DM Mono', monospace;
    color: #f1f5f9;
    letter-spacing: -0.5px;
  }}
  .metric-card .sub {{ color: #475569; font-size: 10px; margin-top: 3px; }}

  /* Layout */
  .two-col {{
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 14px;
    margin-bottom: 14px;
  }}
  .panel {{
    background: #131620;
    border: 1px solid #1e2330;
    border-radius: 8px;
    padding: 15px;
  }}
  .panel-title {{
    font-size: 10px;
    font-family: 'DM Mono', monospace;
    letter-spacing: 1px;
    text-transform: uppercase;
    color: #475569;
    margin-bottom: 10px;
    padding-bottom: 8px;
    border-bottom: 1px solid #1e2330;
  }}

  /* Allocation */
  .alloc-row {{ display: flex; align-items: center; gap: 8px; margin-bottom: 7px; }}
  .alloc-ticker {{ font-family: 'DM Mono', monospace; font-size: 11px; color: #94a3b8; width: 56px; flex-shrink: 0; }}
  .alloc-bar-wrap {{ flex: 1; background: #1e2330; border-radius: 2px; height: 5px; overflow: hidden; }}
  .alloc-bar {{ height: 100%; background: #3b82f6; border-radius: 2px; max-width: 100%; }}
  .alloc-pct {{ font-family: 'DM Mono', monospace; font-size: 10px; color: #64748b; width: 28px; text-align: right; flex-shrink: 0; }}
  .alloc-vol {{ font-family: 'DM Mono', monospace; font-size: 10px; color: #475569; width: 52px; text-align: right; flex-shrink: 0; }}

  /* Lists */
  .panel ul {{ padding-left: 14px; color: #94a3b8; line-height: 1.8; font-size: 12px; }}
  .panel ul li {{ margin-bottom: 3px; }}

  /* Interpretations */
  .interp-block .interp-label {{ font-size: 10px; font-family: 'DM Mono', monospace; color: #475569; text-transform: uppercase; letter-spacing: 0.8px; margin-bottom: 4px; }}
  .interp-block p {{ color: #94a3b8; font-size: 12px; line-height: 1.7; }}

  /* QC */
  .qc-ok {{ color: #22c55e; font-family: 'DM Mono', monospace; font-size: 11px; padding: 6px 0; }}
  .qc-flag {{ font-size: 11px; padding: 6px 10px; border-radius: 4px; margin-bottom: 6px; font-family: 'DM Mono', monospace; line-height: 1.5; }}
  .flag-error {{ background: #ef444415; border-left: 2px solid #ef4444; color: #fca5a5; }}
  .flag-warn  {{ background: #f59e0b15; border-left: 2px solid #f59e0b; color: #fcd34d; }}
  .flag-info  {{ background: #3b82f615; border-left: 2px solid #3b82f6; color: #93c5fd; }}

  /* Model pills */
  .model-pills {{ display: flex; flex-wrap: wrap; gap: 6px; margin-top: 8px; }}
  .pill {{ background: #1e2330; border: 1px solid #2d3548; color: #94a3b8; font-family: 'DM Mono', monospace; font-size: 10px; padding: 3px 8px; border-radius: 3px; }}
  .pill span {{ color: #f1f5f9; font-weight: 500; }}
  /* [CHANGED] Cell 12: amber pill highlight */
  .pill-highlight {{ background: #f59e0b18; border-color: #f59e0b55; color: #fcd34d; }}
  .pill-highlight span {{ color: #f59e0b; }}

  /* Footer */
  .footer {{ margin-top: 18px; padding-top: 10px; border-top: 1px solid #1e2330; color: #334155; font-size: 10px; font-family: 'DM Mono', monospace; display: flex; justify-content: space-between; }}
</style>
</head>
<body>
<div class="dashboard">

  <div class="header">
    <div>
      <h1>Portfolio Risk Agent</h1>
      <div class="sub">LangGraph + Claude · {len(all_results)} client scenarios</div>
    </div>
    <div style="color:#334155;font-size:10px;font-family:'DM Mono',monospace;">{ts} UTC</div>
  </div>

  <div class="tab-bar">
    {tab_buttons}
  </div>

  {tab_panes}

  <div class="footer">
    <span>Generated by Portfolio Risk Agent · LangGraph + Claude Sonnet</span>
    <span>Model configs selected independently per client context</span>
  </div>

</div>
<script>
function switchTab(idx) {{
  document.querySelectorAll(".tab-btn").forEach((b, i) => {{
    b.classList.toggle("active", i === idx);
  }});
  document.querySelectorAll("[id^='pane-wrap-']").forEach((p, i) => {{
    p.style.display = i === idx ? "block" : "none";
  }});
}}
</script>
</body>
</html>'''


# ── Run agent for each scenario ──────────────────────────────
# [CHANGED] Cell 12: pre-cache benchmark ETF data once to avoid rate-limiting
print("Building agent graph...")
agent = build_agent()

print("\nPre-caching benchmark data (SPY, EEM, AGG)...")
_bm_end = datetime.today()
_bm_start = _bm_end - timedelta(days=500)
for _bm in ["SPY", "EEM", "AGG"]:
    try:
        yf.download(_bm, start=_bm_start, end=_bm_end,
                    auto_adjust=True, progress=False)
        print(f"  Cached {_bm}")
    except Exception as e:
        print(f"  Warning: could not pre-cache {_bm}: {e}")

all_results = []
for scenario in CLIENT_SCENARIOS:
    print(f"\n{'='*50}")
    print(f"Running: {scenario['name']} ({scenario['region']} · {scenario['asset_class']})")
    print('='*50)
    state = agent.invoke(make_initial_state(scenario))
    all_results.append((scenario, state))

# ── Render tabbed dashboard ───────────────────────────────────
print("\nRendering multi-client dashboard...\n")
html = build_dashboard_html(all_results)
display(HTML(html))

